CREATE DATABASE CAJERO;

USE CAJERO;

CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(50),
clave VARCHAR(100)
);

CREATE TABLE cuentas (
id INT AUTO_INCREMENT PRIMARY KEY,
saldo_soles DECIMAL(10,2) DEFAULT 0.00,
saldo_dolares DECIMAL(10,2) DEFAULT 0.00,
clave VARCHAR(100)
);

INSERT INTO cuentas VALUES (1,2000,6000,'holamundo');
SELECT * FROM cuentas
